batch_size = 1
img_size = (160, 160)
num_classes = 256
val_samples = 5
epochs = 1
seed=1
train_sample_size = 65
val_sample_size = 12
steps_per_epoch = train_sample_size / batch_size
validation_steps = val_sample_size / batch_size