batch_size = 1
img_size = (160, 160)
num_classes = 5  # TODO change num classes to 2
val_samples = 1
epochs = 1
seed = 1
train_sample_size = 10
val_sample_size = 12
steps_per_epoch = train_sample_size / batch_size
validation_steps = val_sample_size / batch_size
